### ISSUE TITLE
TODO PercivallAkihiko

### ISSUE THREAD

**Issue by PercivallAkihiko** [PercivallAkihiko/metatag#2]
**General**
- [x] Move **Explorer** to the main page
- [x] Add **Contact Us page**
- [x] Improve readability in Javascript
- [x] Fix videos ID
- [x] Cache ethereum's price
- [x] Add edit sell price
- [x] Change voucher code
- [x] Made by noi
- [x] Change icon in **Voucher**
- [x] Add Footer
- [x] Finish Explorer statistics

**Company**
- [x] Separate page
- [x] Add event in **Dashboard**
- [x] Add **Insert video** function in **Votes**
- [x] Finish filters in **Votes**
- [x] Add **Voucher** page
- [x] Fix **Validators** div in **Events**

**Validor**
- [x] Add validator new page **Event**
- [x] Add **Ready** and **Claim All** button in **Vote**
- [x] Add remaining vote inside **Vote Popup**
- [x] Add graphics inside **Vote Popup**
- [x] Add filter in**Vote**
- [x] Add **Voucher**
- [x] Remove **Sell**
- [x] Fix Buy page

**Company's events**
```
BuyTokens(address indexed purchaser, uint amount) (MetaTagToken.sol);
ReceiveTokensFromCompany(address indexed company, uint amount);
AddVideo(address indexed emitter, uint videoId, address[] chosenValidators, uint timestamp);
WithdrawFundsCompany(address indexed company, uint amount);
MTGforVoucher(address indexed validator);
```

**Validator's events**
```
BuyTokens(address indexed purchaser, uint amount) (MetaTagToken.sol);
ReceiveTokensFromValidator(address indexed company, uint amount);
SetVariable(address indexed validator, bool value);
SubmitHash(address indexed validator, address indexed company, uint videoId, bytes32 hash);
RevealHash(address indexed validator, address indexed company, uint videoId, uint[] tags, bytes11 seed);
GetRewards(address indexed validator, address indexed company, uint videoId, uint rewardAmount, bool positive);
WithdrawFundsValidator(address indexed validator, uint amount);
MTGforVoucher(address indexed validator);
```

**Comment by IReallyLikeYourPants** [comment]
- [x] Clean Code
- [x] Comments
- [x] Audio when video is closed (by clicking outside the box) does not stop
- [x] Icon top right of the login with Metamask (circle) 
- [x] Add popup to validators that saved in cache and if change pc save seed somewhere with IDs
- [x] Duplicate tag
- [x] When addVideo event loaded is not showed in All tab I need to click something to show it
- [x] There is no the upper menu in the explorer page
- [x] Add the impossibility to send the transaction with empty tags
- [x] Fix divs and images in the main page (Michele's added the 4 images main1 (2,3,4).png
- [x] In all explorers the hash variable showed through eventsDB is too long 66 characters and go outside the div make it like chosenValidator
