### ISSUE TITLE
TODO IReallyLikeYourPants

### ISSUE THREAD

**Issue by IReallyLikeYourPants** [PercivallAkihiko/metatag#5]
**General**
- [x] Web3.js connections (feat. R4Lpf)
- [x] Clean Sol code
- [x] Clean JS code
- [x] Comment Sol code
- [x] Comment JS code
- [x] Toggle setVariable if validator's tokens < 50
- [ ] Buy Domain?
- [ ] Deploy to Mumbai (Polygon Testnet)
- [x] Limit to one reward and one vote
- [ ] Better getRewards (without cycling all the tags)
- [ ] Better check the duplicate input of the validators
- [ ] Change withdrawFundsValidator() to withdraw from smart contract to account
- [ ] Add another function to every getRewards (separately from the withdraw)
- [x] Owner should not be able to perform buyTokens since it burns only ETHxd
- [x] Need to consent company to perform actions of validator
- [x] Fix withdrawFundsValidator() should not be able to withdraw if video in progress

**Comment by IReallyLikeYourPants** [comment]
Limit to one reward and one vote
